version: "3"

services:
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    depends_on:
      db-service:
        condition: service_healthy
    volumes:
      - .:/app/todo-app
    restart: always
    ports:
      - 3000:3000
  db-service:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    env_file: .env
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
