version: "3"

services:
  todo-app:
    container_name: todo-app
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db-service
    volumes:
      - .:/app/todo-app
    restart: always
    ports:
      - ${WEB_PORT}:3000
  db-service:
    image: postgres:16
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
